### ISSUE TITLE
Invalid character response using requests in Python

### ISSUE THREAD

**Issue by dhimmel** [n1try/telegram-middleman-bot#4]
I'm really excited to message myself via MiddleManBot to alert me when trailhead spots open for the John Muir Trail.

I'm calling the public bot in python as follows:

```python
url = "https://middleman.ferdinand-muetsch.de/api/messages"
payload = {
    'recipient_token': my_token,
    'text': my_text,
    'origin': my_app,
}
import requests
response = requests.post(url, data=payload)
```

I'm getting a response with status code `400`, whose text is:

```
invalid character 'r' looking for beginning of value
```

Any idea what the issue could be?

**Comment by n1try** [comment]
Hey Daniel, I'm glad my bot can help you! I guess what you described is not an issue with the bot itself. Rather you probably need to tell `requests` that your payload is JSON-encoded. Try `response = requests.post(url, json=payload)`. If it doesn't work, get back to me.

**Comment by dhimmel** [comment]
`json=payload` did the trick! Awesome.
