### ISSUE TITLE
Attach file to messages

### ISSUE THREAD

**Issue by stockmind** [n1try/telegram-middleman-bot#7]
How hard could be to implement the possibility to attach a file to the message sent to the bot?

**Comment by n1try** [comment]
That's actually a good idea and shouldn't be too hard to implement.
However, I don't have the time right now, so if anybody wants to contribute....

**Comment by jejoivanic** [comment]
Hello! I forked the project and implemented a solution for this issue. If you create a develop branch I would be glad to make a PR into that branch so you can review it :)

**Comment by n1try** [comment]
Sweet! Thanks for that contribution!
Please just do a PR to `master`. I already took a quick look at your code and I'm going to review it in a little more detail in the next few days.

**Comment by n1try** [comment]
Resolved by #8
